spring:
  application:
    name: reconsiliation
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    async:
      request-timeout: 60000ms
server:
  port: ${PORT:8080}

reconciliation:
  date-window-seconds: 300
  normalize-case: true
  collapse-whitespace: true
  strip-punctuation: false
  compare-wallet-reference: true
  consider-transaction-type: true

api:
  versioning:
    header: X-API-Version
    default-version: "1"
    supported: ["1", "2"]


